import { Application, Router } from "@oak/oak";
import { load } from "std/dotenv/mod.ts";
import { GoogleGenAI } from "@google/genai";
import type { ExecuteWebhookRequest } from "./type.ts";

await load({ export: true });
const ai = new GoogleGenAI({ apiKey: Deno.env.get("GEMINI_API_KEY") });
const signature = Deno.env.get("X_CLIPCROW_SIGNATURE") || null;

const router = new Router();
router.post("/", async (ctx) => {
  if (signature !== ctx.request.headers.get("X-ClipCrow-Signature")) {
    ctx.response.status = 401;
    return;
  }

  const req: ExecuteWebhookRequest = await ctx.request.body.json();
  console.log(req);

  if (req.action === "MCP_SYNC") {
    const { endpoint, token } = req.bot.mcp;
    
    // JSON-RPCリクエストを送信するヘルパー関数
    const rpcRequest = async (method: string, params?: unknown, id: number = 1) => {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${token}`,
        },
        body: JSON.stringify({
          jsonrpc: "2.0",
          method,
          params,
          id,
        }),
      });
      if (!response.ok) {
        throw new Error(`MCP request failed: ${response.statusText}`);
      }
      return await response.json();
    };

    try {
      // Step 1: ツール一覧の取得
      // deno-lint-ignore no-explicit-any
      const listResponse: any = await rpcRequest("tools/list", {}, 1);
      // deno-lint-ignore no-explicit-any
      const tools: any[] = listResponse.result?.tools || [];

      // Step 2: ツール定義の変換 (MCP -> Gemini)
      // deno-lint-ignore no-explicit-any
      const geminiTools = tools.map((tool: any) => ({
        name: tool.name,
        description: tool.description,
        parameters: tool.inputSchema,
      }));

      // Step 3: Gemini API 実行 (Function Calling)
      const result = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        config: {
          tools: [{ functionDeclarations: geminiTools }],
        },
        contents: [
          {
            role: "user",
            parts: [
              {
                text: `MCP設定同期ボタンがクリックされました。
                シリアル番号が ${req.bot.serial_no} のチャットに同期された旨のメッセージを書き出してください。`,
              },
            ],
          },
        ],
      });

      // Step 4: Function Call の処理
      const call = result.functionCalls?.[0];
      if (call) {
        console.log(`Calling tool: ${call.name} with args:`, call.args);
        await rpcRequest("tools/call", {
          name: call.name,
          arguments: call.args,
        }, 2);
        console.log("MCP Sync completed successfully.");
      } else {
        console.warn("MCP Sync: No function call generated by Gemini.");
      }

    } catch (e) {
      console.error("MCP Sync error:", e);
    }

    ctx.response.status = 200;
    return;
  }

  if (req.action === "REACT_BOT_MESSAGE") {
    ctx.response.body = {
      text: `リアクション（ ${req.reaction?.emoji} ）されました。`,
    };
    return;
  }

  if (req.action === "GUEST_USER_CHAT") {
    ctx.response.body = {
      text: `BOTへの質問は、[${req.bot.name}]をメンションに加えてください。`,
    };
    return;
  }

  const model = "gemini-2.5-flash";
  const systemInstruction = 
    "Be clear and short, don't try to answer everything at once," + 
    " and try to keep the conversation going with your users."; 
  let result;

  if (req.history && req.history.length > 0) {
    const history = req.history.map((h) => ({
      role: h.actor.type === "BOT" ? "model" : "user",
      parts: [{ text: h.text }],
    }));
    const chat = ai.chats.create({
      model,
      history,
      config: { systemInstruction },
    });
    result = await chat.sendMessage({
      message: req.current.text,
    });
  } else {
    result = await ai.models.generateContent({
      model,
      contents: req.current.text,
      config: { systemInstruction },
    });
  }

  const text = result.text;
  if (text) {
    console.log(text);
    ctx.response.body = { text };
  } else {
    ctx.response.status = 200;
  }
});

/*
router.post("/log", (ctx) => {
  console.log(ctx.request.body.json());
  ctx.response.status = 200;
});
*/

const app = new Application();
app.use(router.routes());
app.use(router.allowedMethods());
await app.listen({ port: 8080 });
